#!/usr/bin/env python3
# Pretty stupid script to plot data from TI .dat format
# produced using CCS memory dump feature of the debugger.
#
#   Usage: datplot path/to/file
#
import sys
import matplotlib.pyplot as plt
import matplotlib.ticker as ticker

def s32(value):
    return -(value & 0x80000000) | (value & 0x7fffffff)

Y = []
for n, line in enumerate(open(sys.argv[1], 'r')):
    if n > 0:
        v = [s32(int(s, 16)) for s in line[2:].split()]
        Y.append(v[0])

ax=plt.gca()
ax.get_yaxis().get_major_formatter().set_scientific(False)

X = range(len(Y)-1)

# due to what seems to be a matplotlib bug, this doesn't work
# ax.get_yaxis().set_major_formatter(ticker.FormatStrFormatter("%x"))

plt.plot(Y)
plt.show()
