#!/usr/bin/env python3
import matplotlib.pyplot as plt
import numpy as np
import wave
import sys

wavs = [wave.open(f, 'r') for f in sys.argv[1:]]

fig = plt.figure()

maxchannels = 0
for n, wav in enumerate(wavs):
    data = wav.readframes(-1)
    signal = np.fromstring(data, 'Int16')
    channels = wav.getnchannels()
    framerate = wav.getframerate()
    maxchannels = max(channels, maxchannels)

    # before looping, create the ax object required by sharex, sharey
    ax = fig.add_subplot(maxchannels, 1, 1)

    for channel in range(channels):
        ax = fig.add_subplot(maxchannels, 1, channel+1, sharex=ax, sharey=ax)
        ax.plot(signal[channel::channels], label=sys.argv[1+n] + ', channel ' + str(channel))
        plt.ylabel('Amplitude')
        plt.xlabel('Sample')

        plt.legend()
    

plt.show()
